import test from 'node:test'
import assert from 'node:assert/strict'

import { extractDescription } from '../lib/description.js'

test('frontmatter description wins over the body fallback', () => {
  const content = '---\ndescription: From frontmatter\n---\n# Title\n\nA long substantive line that would otherwise be chosen.\n'
  assert.equal(extractDescription(content), 'From frontmatter')
})

test('explicit body description line wins over the fallback', () => {
  const content = '# Title\n\nA long substantive line that appears first.\n\ndescription: From body\n'
  assert.equal(extractDescription(content), 'From body')
})

test('fallback picks the first substantive line, skipping heading and language-switch link', () => {
  const content = '# DeepSeek Harness\n\nEnglish | [中文](README.zh.md)\n\nDeepSeek Harness (`dsh`) is an open-source agent harness developed by [DeepSeek AI](https://deepseek.com).\n'
  assert.equal(
    extractDescription(content),
    'DeepSeek Harness (dsh) is an open-source agent harness developed by DeepSeek AI.',
  )
})

test('fallback skips list, table, blockquote, and horizontal-rule lines', () => {
  const content = '# Title\n\n- item one\n\n| col | col |\n\n> quoted\n\n---\n\nA genuinely substantive prose line that describes the document.\n'
  assert.equal(
    extractDescription(content),
    'A genuinely substantive prose line that describes the document.',
  )
})

test('fallback rejects too-short fragments and picks the first long line', () => {
  const content = '# T\n\nTODO\n\nA full substantive sentence that is long enough to qualify.\n'
  assert.equal(extractDescription(content), 'A full substantive sentence that is long enough to qualify.')
})

test('fallback strips inline Markdown (link, code span, bold)', () => {
  const content = '# T\n\nUse [`dsh`](https://example.com) with **bold** and `code` now.\n'
  assert.equal(extractDescription(content), 'Use dsh with bold and code now.')
})

test('fallback truncates a long line at the last sentence boundary inside the cap', () => {
  const line = `First sentence ends here. ${'a'.repeat(150)}`
  const result = extractDescription(`# T\n\n${line}\n`)
  assert.equal(result, 'First sentence ends here.')
  assert.ok(result.length < 120)
})

test('fallback hard-cut appends an ellipsis when no sentence boundary exists', () => {
  const result = extractDescription(`# T\n\n${'a'.repeat(150)}\n`)
  assert.equal(result, `${'a'.repeat(120)}...`)
})

test('fallback returns null for heading-only or empty bodies', () => {
  assert.equal(extractDescription('# Only a heading\n'), null)
  assert.equal(extractDescription(''), null)
})

test('fallback counts CJK prose by characters, not whitespace words', () => {
  const content = '# 标题\n\n专题 — compact 机制 = 上下文检查点压缩\n'
  assert.equal(extractDescription(content), '专题 — compact 机制 = 上下文检查点压缩')
})

test('fallback never picks a line from inside a fenced code block', () => {
  const content = '# T\n\n```\ndescription: Not this\n```\n\nA real substantive prose line goes here now.\n'
  assert.equal(extractDescription(content), 'A real substantive prose line goes here now.')
})

test('fallback skips a setext heading title and its underline', () => {
  const content = '# T\n\nThis Is A Long Setext Heading Title\n=======================\n\nA real substantive description line follows here now.\n'
  assert.equal(extractDescription(content), 'A real substantive description line follows here now.')
})

test('fallback skips a badge/nav row made only of links and images', () => {
  const badge = '[![Build Status](https://img.shields.io/build)](https://github.com/x) [![Coverage](https://img.shields.io/coverage)](https://github.com/x) [![License](https://img.shields.io/license)](https://github.com/x)'
  const content = `# T\n\n${badge}\n\nA real substantive description line follows here now.\n`
  assert.equal(extractDescription(content), 'A real substantive description line follows here now.')
})

test('fallback truncation skips abbreviation dots and cuts at an earlier boundary', () => {
  const line = `First real sentence ends here; ${'x'.repeat(50)} ctx.${'y'.repeat(40)}`
  const result = extractDescription(`# T\n\n${line}\n`)
  assert.ok(result.endsWith(';'), `expected cut at ';', got: ${JSON.stringify(result)}`)
  assert.ok(!result.includes('ctx'), `abbreviation dot must not be the cut point, got: ${JSON.stringify(result)}`)
})

test('fallback never picks a line from inside an HTML comment', () => {
  const content = '<!-- Generated by scripts — do not edit.\n     Run `pnpm run gen` to regenerate. -->\n\n# Title\n\nA real substantive description line follows here now.\n'
  assert.equal(extractDescription(content), 'A real substantive description line follows here now.')
})
